DECLARE 
	v_string VARCHAR2(200);
BEGIN
	v_string := 
	DBMS_WARNING.GET_WARNING_SETTING_STRING;
	DBMS_OUTPUT.PUT_LINE (v_string);
END;

DECLARE
	v_string VARCHAR2(200);
BEGIN
	v_string := 
	DBMS_WARNING.GET_CATEGORY(7203);
	DBMS_OUTPUT.PUT_LINE(v_string);
END;