/*
GRANT 
CREATE ANY TRIGGER, 
ALTER ANY TRIGGER,
DROP ANY TRIGGER TO C##_USR_PLSQL;

GRANT ADMINISTER DATABASE TRIGGER TO C##_USR_PLSQL;
*/

CREATE TABLE log_table(
	user_id VARCHAR2(30),
	logon_date DATE
);

CREATE OR REPLACE TRIGGER logon_trigg
AFTER LOGON ON DATABASE
BEGIN
	INSERT INTO log_table (user_id, logon_date)
	VALUES (USER, SYSDATE);
END;

