SET SERVEROUTPUT ON;

-- BLOQUE ANÓNIMO SIN SECCIÓN DE DECLARACIÓN
BEGIN 
        DBMS_OUTPUT.PUT_LINE('HOLA QUE TAL');
END;

-- BLOQUE ANÓNIMO CON DECLARACIÓN DE VARIABLES
DECLARE 
    V_DATE DATE := SYSDATE;
BEGIN
    DBMS_OUTPUT.PUT_LINE('LA FECHA ACTUAL ES: ' || V_DATE);
END;

