SET SERVEROUTPUT ON;

DECLARE 
     F_NAME VARCHAR(30);
     L_NAME VARCHAR(30);
     
BEGIN
    SELECT FIRST_NAME, LAST_NAME INTO F_NAME, L_NAME
    FROM EMPLOYEES
    WHERE LAST_NAME = 'King';
    
    DBMS_OUTPUT.PUT_LINE('EL EMPLEADO DEL MES ES: ' || F_NAME || ' ' || L_NAME);
    
EXCEPTION
    WHEN TOO_MANY_ROWS THEN
        DBMS_OUTPUT.PUT_LINE('EL CÓDIGO ESCRITO NO SOPORTA TANTAS FILAS.');
END;

