-- CREACIÓN DE UN USUARIO
CREATE USER C##_USR_PLSQL
IDENTIFIED BY 1234
DEFAULT TABLESPACE users -- Se crean de forma lógica todos los elementos que se quieran usar en la DB
TEMPORARY TABLESPACE temp -- Se guarda temporalmente todos los objetos creados y usados en una sesión.
QUOTA UNLIMITED ON users; -- Se define una capacidad ilimitada para el nuevo usuario en la tabla users.

CREATE ROLE C##_ADMIN;

-- OTORGANDO PRIVILEGIOS A UN ROL
GRANT CREATE SESSION, 
CREATE ANY TABLE, CREATE ANY PROCEDURE, CREATE ANY TRIGGER,
ALTER ANY TABLE, ALTER ANY PROCEDURE, ALTER ANY TRIGGER,
DROP ANY TABLE, DROP ANY PROCEDURE, DROP ANY TRIGGER 
TO C##_ADMIN;

-- REMOVIENDO PRIVILEGIOS DE UN ROL
REVOKE
CREATE ANY TRIGGER, ALTER ANY TRIGGER, DROP ANY TRIGGER
FROM C##_ADMIN;

-- ASIGNANDO UN ROL A UN USUARIO
GRANT C##_ADMIN TO C##_USR_PLSQL;

-- CONSULTADO ROLES Y USUARIOS CREADOS
SELECT * FROM DBA_ROLES;
SELECT * FROM DBA_USERS;

-- CONSULTANDO LOS PRIVILEGIOS ASIGNADOS A UN ROL.
SELECT * FROM DBA_SYS_PRIVS WHERE GRANTEE = 'C##_ADMIN';


















