CREATE OR REPLACE FUNCTION TOMORROW (P_TODAY IN DATE) 
RETURN DATE IS 
    TOMORROW DATE;
BEGIN
    SELECT P_TODAY + 1 INTO TOMORROW 
    FROM DUAL;
    
    RETURN TOMORROW;
END;

CREATE OR REPLACE FUNCTION TOMORROW (P_TODAY IN DATE) 
RETURN DATE IS 
    TOMORROW DATE;
BEGIN
    SELECT P_TODAY + 1 INTO TOMORROW 
    FROM DUAL;

    RETURN TOMORROW;
END;

SELECT TOMORROW(SYSDATE) AS "FECHA DE MAÑANA" FROM DUAL;

BEGIN
    DBMS_OUTPUT.PUT_LINE('LA FECHA ACTUAL ES: ' || TOMORROW(SYSDATE));
END;

SET SERVEROUTPUT ON;