DECLARE 
    V_EMP_COUNT NUMBER;
BEGIN
    DBMS_OUTPUT.PUT_LINE('PL/SQL ES FÁCIL DE USAR');
    
    SELECT COUNT(*) INTO V_EMP_COUNT FROM EMPLOYEES;
    DBMS_OUTPUT.PUT_LINE('HAY ' || V_EMP_COUNT || 'EMPLEADOS EN LA TABLA');
END;

