SET SERVEROUTPUT ON;

CREATE OR REPLACE PROCEDURE PRINT_DATE IS 
    V_DATE VARCHAR(30);
BEGIN
    SELECT TO_CHAR(SYSDATE, 'Month DD, YYYY')
    INTO V_DATE
    FROM DUAL;
    
    DBMS_OUTPUT.PUT_LINE(V_DATE);
END;

BEGIN
    PRINT_DATE;
END;