/*
- Part 2 of the 4th module of Oracle PL/SWL
- Activitie 1
- Estiven Josue Mejia Rodriguez
- 2025/09/11
*/ 

-- DEFINING THE PACKAGE SEPECIFICATION
CREATE OR REPLACE PACKAGE DEPARTAMENTO_PKG
IS
    PROCEDURE CHK_DEPARTAMENTO(P_ID IN NUMBER, V_NOMBRE_DEPARTAMENTO OUT NOCOPY VARCHAR2);
END DEPARTAMENTO_PKG;

-- DEFINING THE PACKAGE BODY
CREATE OR REPLACE PACKAGE BODY DEPARTAMENTO_PKG
IS

    -- FUNCTION IS DEFINED FIRST, BECAUSE IT HAS TO EXIST AFTER THE ELEMENTS THAT USE IT
    FUNCTION VALIDAR_DEPARTAMENTO(P_ID IN NUMBER)
    RETURN BOOLEAN
    IS
        V_EXIST NUMBER;
    BEGIN
        
        SELECT 1 
        INTO V_EXIST 
        FROM DEPARTMENTS 
        WHERE DEPARTMENT_ID = P_ID;
        
        RETURN TRUE;
        
        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                RETURN FALSE;
            WHEN OTHERS THEN
                RETURN FALSE;
    END VALIDAR_DEPARTAMENTO;

    -- DEFINING THE PROCEDURE
    -- IT USES THE FUNCTION TO VALIDATE IF A DEPARTMENT WITH THE ID EXIST.
    PROCEDURE CHK_DEPARTAMENTO(P_ID IN NUMBER, V_NOMBRE_DEPARTAMENTO OUT NOCOPY VARCHAR2)
    IS
    BEGIN
    
        IF VALIDAR_DEPARTAMENTO(P_ID) THEN
        
            SELECT DEPARTMENT_NAME 
            INTO V_NOMBRE_DEPARTAMENTO 
            FROM DEPARTMENTS 
            WHERE DEPARTMENT_ID = P_ID;   
        ELSE 
            DBMS_OUTPUT.PUT_LINE('No existe el departamento con ese id');
            RETURN;
        END IF;
        
    END CHK_DEPARTAMENTO;
END DEPARTAMENTO_PKG;

-- DEFINING AN ANONYMOUS BLOCK TO PROVE/TEST THE PACKAGE ELEMENTS.
DECLARE
    V_NOMBRE_DEPARTAMENTO VARCHAR2(45);
    DEPARTMENT_ID NUMBER := 100;
BEGIN
    DEPARTAMENTO_PKG.CHK_DEPARTAMENTO(DEPARTMENT_ID, V_NOMBRE_DEPARTAMENTO);
    DBMS_OUTPUT.PUT_LINE('DEPARTAMENTO:' || v_nombre_departamento);
END;

SELECT * FROM DEPARTMENTS;

SET SERVEROUTPUT ON;
