CREATE OR REPLACE PROCEDURE insert_emps IS
	TYPE t_emps IS TABLE OF employees%ROWTYPE 
	INDEX BY BINARY_INTEGER;
	
	v_emptab t_emps;
BEGIN

	SELECT * BULK COLLECT INTO v_emptab FROM employees;
	FORALL i IN v_emptab.FIRST .. v_emptab.LAST SAVE EXCEPTIONS
	INSERT INTO employees VALUES v_emptab(i);

EXCEPTION
	WHEN OTHERS THEN
		
		FOR j in 1 .. SQL%BULK_EXCEPTIONS.COUNT LOOP
			DBMS_OUTPUT.PUT_LINE(SQL%BULK_EXCEPTIONS(j).ERROR_INDEX);
			DBMS_OUTPUT.PUT_LINE(SQL%BULK_EXCEPTIONS(j).ERROR_CODE);
		END LOOP;
END isnert_emps;