-- OBJETOS DE SU AUTORIDAD
SELECT * FROM USER_TABLES;

SELECT * FROM USER_INDEXES;

-- OBJETOS A LOS QUE TIENE ACCESO
SELECT * FROM ALL_TABLES;

SELECT * FROM ALL_INDEXES;

-- TODOS LOS OBJETOS DE LA DB (NIVEL DE ADMIN)
SELECT * FROM DBA_TABLES;

SELECT * FROM DBA_INDEXES;
