DECLARE
    V_DATE_OF_JOINING DATE := '02-FEB-2014';
    V_DATE_OF DATE := 'FEBRUARY 02, 2014';
    V_DATE DATE := TO_DATE('FEBRUARY 02, 2014', 'Month DD, YYYY');

BEGIN 
    DBMS_OUTPUT.PUT_LINE(TO_CHAR(SYSDATE, 'Month YYYY'));
END;

BEGIN
    DBMS_OUTPUT.PUT_LINE(TO_DATE('April-1999', 'Month-YYYY'));
END;

DECLARE
    VA VARCHAR(10) := '-123456';
    VB VARCHAR(10) := '+987654';
    VC PLS_INTEGER;
BEGIN
    VC := TO_NUMBER(VA) + TO_NUMBER(VB);
    DBMS_OUTPUT.PUT_LINE(VC);
END;





