-- VAR CHARACTER
DECLARE
    CARACTER CHAR(2) := 'C';
    PALABRA VARCHAR2(20);
    ORACION LONG;
    PARRAFO CLOB;
BEGIN
    DBMS_OUTPUT.PUT_LINE(CARACTER);
END;

-- VAR NUMBER
DECLARE
    NUMERO NUMBER(6,0);
    ENTERO INTEGER;
    ENTERO PLS_INTEGER;
    NUMERO BINARY;
    FLOTANTE CONSTANT FLOAT := 33.4;
BEGIN
    DBMS_OUTPUT.PUT_LINE(FLOTANTE);
END;

-- VAR DATE
DECLARE
    V_DATE1 DATE := '05-APR-2015';
    V_DATE2 DATE := V_DATE1 + 7;
    V_DATE3 TIMESTAMP := SYSDATE;
    V_DATE4 TIMESTAMP WITH TIME ZONE := SYSDATE;
BEGIN
    DBMS_OUTPUT.PUT_LINE(V_DATE1);
END;

-- VAR BOOLEAN
DECLARE
    VVALID1 BOOLEAN := TRUE;
    VVALID2 BOOLEAN; -- NULL
    VVALID2 BOOLEAN NOT NULL := FALSE; 
BEGIN 

    IF VVALID1 THEN
        DBMS_OUTPUT.PUT_LINE('Es V');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Es F');
    END IF;
END;








