DECLARE
    FAM_BIRTHDATE DATE;
    FAM_SIZE NUMBER(2) NOT NULL := 10;
    FAM_LOCATION VARCHAR(13) := 'Florida';
    FAM_BANK CONSTANT NUMBER := 5000;
    FAM_POPULATION INTEGER;
    FAM_NAME VARCHAR(20) DEFAULT 'Roberts';
    FAM_PARTY_SIZE CONSTANT PLS_INTEGER := 20;
    
    RANGO PLS_INTEGER DEFAULT 1;
BEGIN
    DBMS_OUTPUT.PUT_LINE(FAM_NAME);
    DBMS_OUTPUT.PUT_LINE(RANGO);
END;