CREATE OR REPLACE FUNCTION FN_NUM_CHARACTERS(P_STRING IN VARCHAR2)
RETURN INTEGER IS
    V_NUM_CHARACTERS INTEGER;
BEGIN
    -- SELECT LENGTH(P_STRING) INTO V_NUM_CHARACTERS FROM DUAL;
    V_NUM_CHARACTERS := LENGTH(P_STRING);
    RETURN V_NUM_CHARACTERS;
END;

DECLARE 
    V_LENGTH_OF_STRING INTEGER;
BEGIN
    V_LENGTH_OF_STRING := FN_NUM_CHARACTERS('Oracle Corporation');
    DBMS_OUTPUT.PUT_LINE(V_LENGTH_OF_STRING);
END;

/*
BEGIN
    DBMS_OUTPUT.PUT_LINE(FN_NUM_CHARACTERS('ESTIVEN MEJIA'));
END;
*/