DECLARE 
-- vari varchar2(15) := 'hola que hace';
random_var BRANDS.BRAND_ID%type := 20;
num_var number(10, 2) := 12.3;
/*
EL TIPO DE DATO BYTE SOLO PERMITE EXACTAMENTE 16 CARACTERES QUE OCUPEN EXACTAMENTE 4 BITS DE ESPACIO.
ESTE TIPO DE DATO PUEDE PROVOCAR PROBLEMAS EN CASO DE INGRESAR CARACTERES EN OTRO IDIOMA O DE TIPO UTF-8

SOLO FUNCIONA DE FORMA EFICIENTE CON LOS DATOS DE TIPO ASCII.
*/
var_var varchar2(16 byte) := 'aaaaaaaaaaaaaaaaa';
/*
ES MÁS FACTIBLE HACER USO DEL TIPO DE DATO 'CHAR', YA QUE PERMITE LA CANTIDAD INDICADA DE CARACTERES SIN IMPORTAR
SI ESTOS CARATERES SON DE TIPO MULTIVARIABLE.
ESTE TIPO DE DATO ES BENEFICIOSO CUANDO SE USAN CARACTERES DE TIPO UTF-8

*/
var2_var2 varchar2(16 char) := 'aaaaaaaaaaaaaaaaa';

BEGIN 

dbms_output.put_line('hola que hace' || ' ' || random_var || ' ' || var_var);

END;

set serveroutput on;

SELECT * FROM BRANDS;