DECLARE 
VALOR_INICIAL NUMBER(3) := 0;
VALOR_FINAL NUMBER(3) := 6;
FECHA DATE;

BEGIN 
-- DECLARACIÓN DE UN FOR
-- LA VARIABLE ITERACION SE DEFINE Y ASIGNA UN VALOR EN LA DECLARACIÓN DEL FOR.
FOR ITERACION IN VALOR_INICIAL .. VALOR_FINAL LOOP

    FECHA := SYSDATE + ITERACION;
    DBMS_OUTPUT.PUT_LINE('Número de ciclo es: ' || ITERACION);
    DBMS_OUTPUT.PUT_LINE(FECHA);
END LOOP;

END;

SET SERVEROUTPUT ON;