-- LO VISTO EN EL VÍDEO NO ESTÁ COMPLETO SI SE CONSIDERA TAMBIÉN LO VISTO EN CLASE.
DECLARE

    FECHA DATE;
    FECHA_HORA TIMESTAMP;
    
BEGIN

    FECHA := SYSDATE;
    FECHA_HORA := SYSTIMESTAMP;
    
    DBMS_OUTPUT.PUT_LINE(FECHA_HORA);    
    -- ESTAS FUNCIONES SIRVEN PARA ALMACENAR DATOS EN EL FORMATO CORRECTO DE FECHA EN LA BD.
    -- Si llegan cadenas de fechas con formato incorrecto, se puede hacer la conversion con estas funciones.
    /*
    FECHA := TO_DATE('19870121', 'YYYY-MM-DD');
    FECHA_HORA := TO_TIMESTAMP('2020/01/21 12:23:56', 'YYYY-MM-DD HH:MI:SS');
    
    DBMS_OUTPUT.PUT_LINE('EL TEXTO CONVERTIDO A TIPO DATE ES: ' || FECHA);
    DBMS_OUTPUT.PUT_LINE('EL TEXTO CONVERTIDO A TIPO TIMESTAMP ES:' || FECHA_HORA);
    */
        
    -- TO_CHAR() es para convertir las fechas al tipo de formato que se desee.
    -- HH por defecto mantiene el formato de 12 horas. Si se desea especificar entre día y noche se agrega "AM" al final del formato de la hora.
    -- Para usar el formato de 24 horas se usa "HH24"
    -- REVISE LOS APUNTES PARA MÁS INFORMACIÓN (ES MUCHA).
    DBMS_OUTPUT.PUT_LINE('LA FECHA (DATE) CONVERTIDA A UNA CADENA CON FORMATO PERSONALIZADO ES: ' || TO_CHAR(FECHA, 'DD/MON/YYYY', 'NLS_DATE_LANGUAGE = SPANISH'));
    DBMS_OUTPUT.PUT_LINE('LA FECHA (TIMESTAMP) CONVERTIDA A UNA CADENA CON FORMATO PERSONALIZADO ES: ' || TO_CHAR(FECHA_HORA, 'DD/MM/YYYY HH:MI:SS AM'));    
    
    DBMS_OUTPUT.PUT_LINE('CAMBIANDNO IDIOMA DE LA FECHA: ' || TO_CHAR(FECHA, 'DAY/MONTH/YYYY', 'NLS_DATE_LANGUAGE = SPANISH'));


    DBMS_OUTPUT.PUT_LINE('USUARIO CONECTADO:' || USER);
END;

SELECT ORDER_DATE, TO_DATE(ORDER_DATE, 'YYYYMMDD') FROM ORDERS;
SELECT CATEGORY_NAME, SUBSTR(CATEGORY_NAME, 1, 5) FROM CATEGORIES;

SET SERVEROUTPUT ON;

