DECLARE 
ITERACION NUMBER(3) := 0;
FECHA TIMESTAMP := SYSDATE;

BEGIN

-- DEFINICIÓN DE UN CICLO WHILE.
WHILE (ITERACION < 3) LOOP
    FECHA := SYSDATE + ITERACION;
    DBMS_OUTPUT.PUT_LINE('Número de ciclo: ' || ITERACION);
    DBMS_OUTPUT.PUT_LINE(FECHA);
    ITERACION := ITERACION + 1;

END LOOP;

END;

SET SERVEROUTPUT ON;