DESC ORDER_ITEMS;
ALTER TABLE ORDER_ITEMS MODIFY IMPUESTO NUMBER(10, 2) DEFAULT NULL;
SELECT * FROM ORDER_ITEMS;

------------------------------------------------------------------------------------------------

-- PROCEDIMIENTO CON PARÁMETROS QUE SE USARÁ EN EL JOB.
CREATE OR REPLACE PROCEDURE SP_CALCULA_IMPUESTO(VALOR_IMP NUMBER, PROD_ACTUALIZAR NUMBER)
IS
BEGIN
    IF (PROD_ACTUALIZAR =0) THEN
        UPDATE ORDER_ITEMS SET IMPUESTO = ((QUANTITY*LIST_PRICE)*VALOR_IMP) WHERE IMPUESTO = 0 OR IMPUESTO IS NULL;
    ELSE
        IF (PROD_ACTUALIZAR = 1) THEN
            UPDATE ORDER_ITEMS SET IMPUESTO = ((QUANTITY*LIST_PRICE)*VALOR_IMP);
        END IF;
    END IF;
END;

------------------------------------------------------------------------------------------------

-- CREACIÓN DE UN JOB CON PARÁMETROS.
BEGIN
    DBMS_SCHEDULER.CREATE_JOB(
        JOB_NAME => 'JOB_ACTUALIZA_IMPUESTO',
        JOB_TYPE => 'STORED_PROCEDURE',
        JOB_ACTION => 'SP_CALCULA_IMPUESTO',
        NUMBER_OF_ARGUMENTS => 2,
        START_DATE => TO_TIMESTAMP('2024-12-12 13:35:00','YYYY-MM-DD HH24:MI:SS'),
        REPEAT_INTERVAL => 'FREQ=MONTHLY; BYMONTHDAY=12; BYHOUR=13; BYMINUTE=35; BYSECOND=0',
        ENABLED => FALSE -- SI EL OBJETO TIENE PARÁMEETROS, EL JOB SE INHABILITA.
    );
END;

------------------------------------------------------------------------------------------------

-- LOS VALORES QUE SE ENVÍAN A LOS PARÁMETROS DEL OBJETO QUE EJECUTA EL JOB SON ESTÁTICOS.
BEGIN
    -- FUNCIÓN PARA DEFINIR UN VALOR A LOS PARÁMETROS DEL OBJETO QUE EJECUTA EL JOB.
    DBMS_SCHEDULER.SET_JOB_ARGUMENT_VALUE(
        JOB_NAME => 'JOB_ACTUALIZA_IMPUESTO',
        ARGUMENT_POSITION => 1,
        ARGUMENT_VALUE => 1
    );
    
    -- SE DEFINE UNA FUNCIÓN POR CADA PARÁMETRO.
    DBMS_SCHEDULER.SET_JOB_ARGUMENT_VALUE(
        JOB_NAME => 'JOB_ACTUALIZA_IMPUESTO',
        ARGUMENT_POSITION => 2,
        ARGUMENT_VALUE => 1
    );
END;

------------------------------------------------------------------------------------------------

-- UNA VEZ DEFINIDOS LOS PARÁMETROS PARA EL OBJETO, SE TIENE QUE HABILITAR EL JOB.
-- FUNCIÓN PARA HABILITAR UN JOB.
BEGIN 
    DBMS_SCHEDULER.ENABLE('JOB_ACTUALIZA_IMPUESTO');
END;

------------------------------------------------------------------------------------------------

-- FUNCIÓN PARA ELIMINAR UN JOB.
BEGIN
    DBMS_SCHEDULER.DROP_JOB(
        JOB_NAME => 'JOB_ACTUALIZA_IMPUESTO'
    );
END;

SELECT * FROM USER_SCHEDULER_JOBS;
SELECT JOB_NAME, LOG_DATE, STATUS FROM USER_SCHEDULER_JOB_LOG;


BEGIN
    -- FUNCTION TO EXECUTE A JOB MANUALLY.
    DBMS_SCHEDULER.RUN_JOB(
        JOB_NAME => 'JOB_ACTUALIZA_IMPUESTO'
    );
END;
















