-- EXECUTES THE BODY ONLY ONE TIME
-- WHEN ANY DML STATEMENT OCCURS

CREATE OR REPLACE TRIGGER log_dept_changes
AFTER INSERT OR UPDATE OR DELETE ON DEPARTMENTS
BEGIN
	INSERT INTO log_dept_table (which_user, when_done)
	VALUES (USER, SYSDATE);
END;