ALTER SESSION SET PLSQL_CODE_TYPE = INTERPRETED;

ALTER SESSION SET PLSQL_CODE_TYPE = NATIVE;

CREATE OR REPLACE PROCEDURE sqlproc 
IS 
	v_count PLS_INTEGER;
BEGIN
	FOR i IN 1 .. 50000 LOOP 
		SELECT COUNT(*) INTO v_count FROM countries;
	END LOOP;
END sqlproc;

-- In this example, INTERPRETED is faster
BEGIN
	sqlproc;
END;