-- CREATE A FUNCTION THAT RETRIEVES A CATEGORY NAME BY ITS ID FROM THE CATEGORIES TABLE
CREATE OR REPLACE FUNCTION FN_NOMBRE_CATEGORIA(ID_CAT NUMBER, NOMB_CAT OUT VARCHAR2)
RETURN VARCHAR2
IS
    NOMBRE_CATEGORIA CATEGORIES.CATEGORY_NAME%TYPE;
BEGIN
    SELECT CATEGORY_NAME INTO NOMBRE_CATEGORIA FROM CATEGORIES WHERE CATEGORY_ID = ID_CAT;
    
    NOMB_CAT := NOMBRE_CATEGORIA;
    RETURN NOMBRE_CATEGORIA;
END;

DECLARE
    NOMBRE CATEGORIES.CATEGORY_NAME%TYPE;
    NOMB_CAT VARCHAR2(255);
BEGIN 
    NOMBRE := FN_NOMBRE_CATEGORIA(4, NOMB_CAT);
    DBMS_OUTPUT.PUT_LINE('CATEGORIA OBTENIDA DESDE EL RETORNO:' || NOMBRE);
    DBMS_OUTPUT.PUT_LINE('CATEGORIA OBTENIDA DESDE LOS PARÁMETROS:' || NOMB_CAT);
END;