-- CREATE A FUNCTION THAT RETURNS ALL THE CATEGORIES.
CREATE OR REPLACE FUNCTION FN_INF_CATEGORIAS
RETURN SYS_REFCURSOR
IS
    CDATOS SYS_REFCURSOR;
BEGIN
    OPEN CDATOS FOR SELECT CATEGORY_ID, CATEGORY_NAME FROM CATEGORIES WHERE CATEGORY_ID > 3;
    RETURN CDATOS;
END;

DECLARE 
    DATOS_CAT SYS_REFCURSOR;
    REGISTRO CATEGORIES%ROWTYPE;
BEGIN
    DATOS_CAT := FN_INF_CATEGORIAS;
    
    LOOP    
        FETCH DATOS_CAT INTO REGISTRO;
        EXIT WHEN DATOS_CAT%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('EL ID DE LA CATEGORIA ES: ' || REGISTRO.CATEGORY_ID);
        DBMS_OUTPUT.PUT_LINE('EL NOMBRE DE LA CATEGORIA ES ' || REGISTRO.CATEGORY_NAME);
        DBMS_OUTPUT.PUT_LINE(CHR(10));
    END LOOP;
END;

SET SERVEROUTPUT ON;