-- CREATE A FUNCTION THAT RETRIEVES THE VALUES: NOMBRE_TIENDA, TELEFONO, CORREO AND CALLE FROM THE STORES TABLE. THIS HAS TO BE RETRIEVED IN BASE FROM THE STORE ID
CREATE OR REPLACE FUNCTION FN_DATOS_TIENDA(ID_TIENDA STORES.STORE_ID%TYPE)
RETURN STORES%ROWTYPE
IS
    REGISTRO STORES%ROWTYPE;
BEGIN 
    SELECT * INTO REGISTRO FROM STORES WHERE STORE_ID = ID_TIENDA;
    RETURN REGISTRO;
END;

DECLARE
    REGISTRO STORES%ROWTYPE;
BEGIN
    REGISTRO := FN_DATOS_TIENDA(4);
    
    DBMS_OUTPUT.PUT_LINE('NOMBRE DE LA TIENDA ES' || REGISTRO.STORE_NAME);
    DBMS_OUTPUT.PUT_LINE('TELEFONO DE LA TIENDA ES' || REGISTRO.PHONE); 
    DBMS_OUTPUT.PUT_LINE('CORREO DE LA TIENDA ES' || REGISTRO.EMAIL);
    DBMS_OUTPUT.PUT_LINE('DIRECCION DE LA TIENDA ES' || REGISTRO.CITY);

END;

DESC STORES;