-- CREAR UN PROCEDIMIENTO QUE ENVÍA TODOS LOS ELEMENTOS PARA INSERTAR EN UNA TABLA
-- CREAR UN PROCEDIMIENTO QUE SE ENCARGUE DE REALIZAR UNA INSERCIÓN EN LA TABLA
-- VER EL MANEJO DE TRANSACCIONES A NIVEL DE PROCEDIMIENTOS ALMACENADOS
CREATE OR REPLACE PROCEDURE SP_VALORES_REG_STAFF(ID_STAFF NUMBER, NOMBRE VARCHAR2, APELLIDO VARCHAR2, CORREO VARCHAR2,
                                                TELEFONO VARCHAR2, ACTIVO NUMBER, ID_STORE NUMBER, ID_MANAGER NUMBER)
IS
    MSJ NUMBER;
BEGIN
    SP_INSERT_STAFFS(ID_STAFF, NOMBRE, APELLIDO, CORREO, TELEFONO, ACTIVO, ID_STORE, ID_MANAGER, MSJ);
    
    IF(MSJ = 1) THEN
        COMMIT;
    ELSIF(MSJ =2) THEN
        ROLLBACK;
    END IF;
END;


CREATE OR REPLACE PROCEDURE SP_INSERT_STAFFS(ID_STAFF NUMBER, NOMBRE VARCHAR2, APELLIDO VARCHAR2, CORREO VARCHAR2, TELEFONO VARCHAR2,
                                            ACTIVO NUMBER, ID_STORE NUMBER, ID_MANAGER NUMBER, MSJ OUT NUMBER)
IS

BEGIN
    INSERT INTO STAFFS VALUES (ID_STAFF, NOMBRE, APELLIDO, CORREO, TELEFONO, ACTIVO, ID_STORE, ID_MANAGER);
    MSJ := 1;
    
    EXCEPTION
    WHEN OTHERS THEN
        MSJ := 2;
    
END;

EXECUTE SP_VALORES_REG_STAFF(7, 'JOSUE', 'RODRÍGUEZ', 'josue.rodriguez@unah.hn', '97045770', 2, 3, 3);
-- DESC STAFFS;
SELECT * FROM STAFFS;