DECLARE 

    -- De esta forma se define un RECORD.
    TYPE FILA IS RECORD(
        NOMBRE PRODUCTS.PRODUCT_NAME%TYPE,
        CATEGORIA CATEGORIES.CATEGORY_NAME%TYPE, 
        MODELO PRODUCTS.PRODUCT_NAME%TYPE
    );
    
    CURSOR CDATOS_PRODUCTOS IS SELECT PRODUCTS.PRODUCT_NAME, CATEGORIES.CATEGORY_NAME, PRODUCTS.MODEL_YEAR FROM PRODUCTS
    INNER JOIN CATEGORIES ON PRODUCTS.CATEGORY_ID = CATEGORIES.CATEGORY_ID;
    
    -- El RECORD definido anteriormente debe ser definido a una variable para poder hacer uso de su estructura.
    DATOS_PRODUCTOS FILA;

    
BEGIN
    OPEN CDATOS_PRODUCTOS;
    LOOP
        FETCH CDATOS_PRODUCTOS INTO DATOS_PRODUCTOS;
        EXIT WHEN CDATOS_PRODUCTOS%NOTFOUND;
        -- Se debe definir el nombre de las llaves del diccionario para poder acceder a los valores obtenidos de la DB.
        DBMS_OUTPUT.PUT_LINE('EL NOMBRE DEL PRODUCTO ES:' || DATOS_PRODUCTOS.NOMBRE);
        DBMS_OUTPUT.PUT_LINE('EL NOMBRE DE LA CATEGORIA DEL PRODUCTO ES: ' || DATOS_PRODUCTOS.CATEGORIA);
        DBMS_OUTPUT.PUT_LINE('EL AÑO DEL MODELO DEL PRODUCTO ES: ' || DATOS_PRODUCTOS.MODELO || CHR(10));
    END LOOP;
    CLOSE CDATOS_PRODUCTOS;
END;

SET SERVEROUTPUT ON;