DECLARE 
    NOMBRE_PRODUCTO PRODUCTS.PRODUCT_NAME%TYPE;
    MODELO_PRODUCTO PRODUCTS.MODEL_YEAR%TYPE;
    NOMBRE_CATEGORIA CATEGORIES.CATEGORY_NAME%TYPE;
    
    CURSOR CDATOS_PRODUCTO IS 
    SELECT PRODUCT_NAME, MODEL_YEAR, CATEGORY_NAME FROM PRODUCTS
    INNER JOIN CATEGORIES ON PRODUCTS.CATEGORY_ID = CATEGORIES.CATEGORY_ID;
BEGIN
    OPEN CDATOS_PRODUCTO;
    LOOP
        FETCH CDATOS_PRODUCTO INTO NOMBRE_PRODUCTO, MODELO_PRODUCTO, NOMBRE_CATEGORIA;
        EXIT WHEN CDATOS_PRODUCTO%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('EL NOMBRE DEL PRODUCTO ES: ' || NOMBRE_PRODUCTO);
        DBMS_OUTPUT.PUT_LINE('EL MODELO DEL PRODUCTO ES: ' || MODELO_PRODUCTO);
        DBMS_OUTPUT.PUT_LINE('EL NOMBRE DE LA CATEGORIA ES: ' || NOMBRE_CATEGORIA || CHR(10));
    END LOOP;
    CLOSE CDATOS_PRODUCTO;
END;

SET SERVEROUTPUT ON;