DECLARE
    NOMBRE_PRODUCTO PRODUCTS.PRODUCT_NAME%TYPE;
    CURSOR CNOMBRE_PRODUCTO IS SELECT PRODUCT_NAME FROM PRODUCTS;
BEGIN

    IF(CNOMBRE_PRODUCTO%ISOPEN) THEN
        CLOSE CNOMBRE_PRODUCTO;
    END IF;
    OPEN CNOMBRE_PRODUCTO;
    LOOP
        -- Se tiene que hacer el FETCH primero que la condición de salida para que la variable NOTFOUND sea verdadera.
        FETCH CNOMBRE_PRODUCTO INTO NOMBRE_PRODUCTO; 
        EXIT WHEN (CNOMBRE_PRODUCTO%NOTFOUND);
        DBMS_OUTPUT.PUT_LINE(CNOMBRE_PRODUCTO%ROWCOUNT || '. ' || NOMBRE_PRODUCTO);
    END LOOP;
    CLOSE CNOMBRE_PRODUCTO;
END;
-- SET SERVEROUTPUT ON;