DECLARE 

    NOMBRE PRODUCTS.PRODUCT_NAME%TYPE;
    FECHA DATE;
BEGIN

    FECHA := 'HOLA MUNDO';
    SELECT PRODUCTS.PRODUCT_NAME INTO NOMBRE FROM PRODUCTS;
    
    DBMS_OUTPUT.PUT_LINE('EL NOMBRE DEL PRODUCTO ES:' || NOMBRE);
    
    EXCEPTION
        WHEN TOO_MANY_ROWS THEN
            DBMS_OUTPUT.PUT_LINE('ERROR AL INTENTAR OBTENER MÁS DE UN REGISTRO');
            DBMS_OUTPUT.PUT_LINE('CÓDIGO Y MENSAJE DEL ERROR: ' || SQLCODE || ' Y ' || SQLERRM);
            
        WHEN OTHERS THEN
            IF(SQLCODE = -1858) THEN
                DBMS_OUTPUT.PUT_LINE('ERROR -1858');
                DBMS_OUTPUT.PUT_LINE('CÓDIGO Y MENSAJE DEL ERROR: ' || SQLCODE || ' Y ' || SQLERRM);
                
            END IF;
END;

-- SET SERVEROUTPUT ON;