-- CREACIÓN DE UN TG QUE RELACIONA UNA SECUENCIA AL ID DE UNA TABLA ANTES DE HACER UNA INSERCIÓN DE DATOS.
CREATE OR REPLACE TRIGGER TG_SQ_TABLA_CATEGORIAS
BEFORE INSERT ON CATEGORIES
FOR EACH ROW
DECLARE

BEGIN
    -- SE ESTÁ RELACIONANDO EL VALOR DE LA SQ AL ID DE LA NUEVA FILA QUE SE INSERTARÁ.
    :NEW.CATEGORY_ID:= SQ_TABLA_CATEGORIAS.NEXTVAL;
END;


DESC CATEGORIES;
SELECT * FROM CATEGORIES;

INSERT INTO CATEGORIES(CATEGORY_NAME) VALUES ('INSERTADO CON TG 1');
INSERT INTO CATEGORIES(CATEGORY_NAME) VALUES ('INSERTADO CON TG 2');