-- CREANDO UNA SECUENCIA
CREATE SEQUENCE SQ_BITACORAS START WITH 1 INCREMENT BY 1 NOCACHE;

-- CREACION DEL TRIGGER
CREATE OR REPLACE TRIGGER TG_CATEGORIAS
BEFORE INSERT ON CATEGORIES
FOR EACH ROW 
DECLARE
    -- ESTA LÍNEA PERMITE AL TRIGGER GESTIONAR SUS PROPIOS COMMIT Y ROLLBACK.
    -- DE ESTA FORMA LOS POSIBLES ERRORES DEL TRIGGER NO LLEGAN HASTA LA EXCEPCION QUE PERTENECE AL COMANDO QUE LO HA DISPARADO.
    PRAGMA AUTONOMOUS_TRANSACTION;

-- CREANDO INSERCIONES EN LA TABLA BITACORAS QUE DESCRIBEN LAS ACCIONES REALIZADAS EN LA TABLA CATEGORIES DE LA BASE DE DATOS.    
BEGIN
    INSERT INTO BITACORAS VALUES(SQ_BITACORAS.NEXTVAL, 'SE REALIZÓ UN INSERT EN LA TABLA CATEGORIAS CON ID: ' || :NEW.CATEGORY_ID || 
    ' Y NOMBRE:' || :NEW.CATEGORY_NAME,
    SYSTIMESTAMP, USER, 'OPERACION INSERT');
    COMMIT; -- Se puede realizar COMMIT en el TIGGER porque se ha declarado PRAGMA AUTONOMOUS_TRANSACTION
    
    -- Se puede gestionar errores y realizar ROLLBACK ya que se está utilizando PRAGMA para manejar los errores del TRIGGER dentro del mismo.
    EXCEPTION
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('THE ERROR CODE IS: ' || SQLCODE);
            ROLLBACK;
END;

-- INSERTANDO UN VALOR EN LA TABLA CATEGORIES PARA DISPARAR EL TRIGGER
BEGIN
    INSERT INTO CATEGORIES VALUES(1,'INSERTANDO CON EL TRIGGER DE PRAGMA');
    COMMIT;
    SAVEPOINT PT1;
    
    INSERT INTO CATEGORIES VALUES(1,'INSERCIÓN 2 CON EL TRIGGER DE PRAGMA');
    COMMIT;
    SAVEPOINT PT1;
    
    EXCEPTION
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('XD');
            ROLLBACK TO SAVEPOINT PT1;
            
END;

SET SERVEROUTPUT ON;
