CREATE OR REPLACE TRIGGER TG_INSERTA_BRANDS
BEFORE INSERT ON BRANDS
FOR EACH ROW
DECLARE
BEGIN

    :NEW.BRAND_NAME:= TRIM(UPPER(:NEW.BRAND_NAME));
END;

BEGIN
    INSERT INTO BRANDS VALUES(8 ,'  Alhpina  ');  
    COMMIT;
END;

SET SERVEROUTPUT ON;