-- CREAR FUNCION QUE RETORNE TODAS LAS ORDENES Y LOS CLIENTES QUE HAN HECHO UNA ORDEN
-- SE DEBEN RETORNAR EL CAMPO ORDER_ID, ORDER_DATE, SHIPPED_DATE, CUSTOMER_ID, FIRST_NAME, LAST_NAME 

CREATE OR REPLACE FUNCTION FN_INF_ORDEN_CLIENTES
RETURN SYS_REFCURSOR
IS
    CDATOS SYS_REFCURSOR;
BEGIN
    OPEN CDATOS FOR SELECT ORDERS.ORDER_ID, ORDERS.ORDER_DATE, ORDERS.SHIPPED_DATE, 
    CUSTOMERS.CUSTOMER_ID, CUSTOMERS.FIRST_NAME, CUSTOMERS.LAST_NAME
    FROM ORDERS
    INNER JOIN CUSTOMERS ON ORDERS.CUSTOMER_ID = CUSTOMERS.CUSTOMER_ID;
    
    RETURN CDATOS;
END;

DECLARE
    DATOS_CAT SYS_REFCURSOR;
    
    ORDER_ID ORDERS.ORDER_ID%TYPE;
    ORDER_DATE ORDERS.ORDER_DATE%TYPE;
    SHIPPED_DATE ORDERS.SHIPPED_DATE%TYPE;
    CUSTOMER_ID CUSTOMERS.CUSTOMER_ID%TYPE;
    FIRST_NAME CUSTOMERS.FIRST_NAME%TYPE;
    LAST_NAME CUSTOMERS.LAST_NAME%TYPE;
BEGIN
    DATOS_CAT := FN_INF_ORDEN_CLIENTES;
    
    LOOP
        FETCH DATOS_CAT INTO ORDER_ID, ORDER_DATE, SHIPPED_DATE, CUSTOMER_ID, FIRST_NAME, LAST_NAME;
        EXIT WHEN DATOS_CAT%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('EL ID DE LA ORDEN ES: ' || ORDER_ID);
        DBMS_OUTPUT.PUT_LINE('FECHA DE ENVIO DE LA ORDEN: ' || SHIPPED_DATE);
        DBMS_OUTPUT.PUT_LINE('EL ID DEL CLIENTE ES: ' || CUSTOMER_ID);
        DBMS_OUTPUT.PUT_LINE('EL NOMBRE DEL CLIENTE ES: ' || FIRST_NAME);
        DBMS_OUTPUT.PUT_LINE('EL APELIDO DEL CLIENTE ES: ' || LAST_NAME);
        DBMS_OUTPUT.PUT_LINE(CHR(10));
    
    END LOOP;
END;
    