-- CREAR UN SP QUE OBTIENE EL VALOR DE LAS CATEGORIAS E IMPRIME EL VALOR OBTENIDO
-- EL NOMBRE SE DEBE OBTENER DE LA CATEGORIA = 2
CREATE OR REPLACE PROCEDURE SP_OBTENER_NOMB_CAT(IDCAT IN NUMBER, NOMBRE_CAT OUT CATEGORIES.CATEGORY_NAME%TYPE)
IS
    -- NOMBRE_CAT CATEGORIES.CATEGORY_NAME%TYPE;
BEGIN
    SELECT CATEGORIES.CATEGORY_NAME INTO NOMBRE_CAT FROM CATEGORIES WHERE CATEGORY_ID = IDCAT;
    
    -- HABILITAR LINEA DE IMPRESIÓN EN PANTALLA SI SE LLAMA EL SP POR MEDIO DE LA PALABRA EXECUTE.
    -- DBMS_OUTPUT.PUT_LINE('EL NOMBRE DE LA CATEGORIA ES:' || NOMBRE_CAT);
END;

-- USANDO BLOQUE ANONIMO PARA LLAMAR A UN PROCEDIMIENTO ALMACENADO
DECLARE
    NOM_CAT CATEGORIES.CATEGORY_NAME%TYPE;
BEGIN
    SP_OBTENER_NOMB_CAT(2, NOM_CAT);
    DBMS_OUTPUT.PUT_LINE('EL NOMBRE DE LA CATEGORIA ES:' || NOM_CAT);
END;


-- EXECUTE SP_OBTENER_NOMB_CAT(2);
--SET SERVEROUTPUT ON;

-- LLAMANDO EL PROCEDIMIENTO DENTRO DE UN BLOQUE ANONIMO
