-- CREAR UN SP SIN PARÁMETROS QUE OBTENGA EL TOTAL DE LOS PRODUCTOS
CREATE OR REPLACE PROCEDURE SP_CANT_PRODS 
IS
    CANTIDAD NUMBER;
BEGIN
    SELECT COUNT(*) INTO CANTIDAD FROM PRODUCTS;
    DBMS_OUTPUT.PUT_LINE('LA CANTIDAD DE PRODUCTOS GUARDADOS ES:' || CANTIDAD);
END;

EXECUTE SP_CANT_PRODS;