-- CREATE SEQUENCE THAT WE'LL USE TO INSERT SEQUENTIAL VALUES IN THE PRODUCTS' INDEX
CREATE SEQUENCE SQ_PRODUCTS_ID
START WITH 7 
INCREMENT BY 1;

-- USE THIS TRIGGER TO PUT A INDEX SEQUENTIAL VALUE FOR EACH INSTANCE INSERTED IN THE PRODUCTS TABLE
CREATE OR REPLACE TRIGGER TG_SQ_PRODUCTS
BEFORE INSERT ON PRODUCTS
FOR EACH ROW
DECLARE
BEGIN
    :NEW.PRODUCT_ID:=SQ_PRODUCTS_ID.NEXTVAL;
END;

CREATE OR REPLACE PROCEDURE SP_INSERTA_PRODUCTO(NOMB_PROD VARCHAR2, ID_BRAND NUMBER, CAT_ID NUMBER, ANIO_MODELO NUMBER, PRECIO NUMBER, MSJEXITO OUT VARCHAR2, MSJERROR OUT VARCHAR2)
IS
BEGIN
    -- USE THE NEXT AVAILABLE INDEX TO INSERT THE NEW VALUE IN THE TABLE
    INSERT INTO PRODUCTS (PRODUCT_NAME, BRAND_ID, CATEGORY_ID, MODEL_YEAR, LIST_PRICE) VALUES(NOMB_PROD, ID_BRAND, CAT_ID, ANIO_MODELO, PRECIO);
    COMMIT;
    MSJEXITO := 'INSERCIÓN EXITOSA';
    
    EXCEPTION
    WHEN OTHERS THEN
        MSJERROR := SQLERRM; 
END;

-- SELECT * FROM PRODUCTS;

DECLARE
    MSJEXITO VARCHAR2(255);
    MSJERROR VARCHAR2(255);
BEGIN
    SP_INSERTA_PRODUCTO('BICICLETA DE MONTAÑA', 1, 4, 2019, 4345, MSJEXITO, MSJERROR);
    DBMS_OUTPUT.PUT_LINE(MSJEXITO || ' ' || MSJERROR);
END;

-- SET SERVEROUTPUT ON;