SELECT * FROM BRANDS;

CREATE OR REPLACE PROCEDURE SP_NOMB_BRAND_MAYUS 
IS
BEGIN
    UPDATE BRANDS SET BRAND_NAME = UPPER(BRAND_NAME);
    COMMIT;
END;

DECLARE
BEGIN
-- SINTAXIS USADA PARA CREAR UN JOB
DBMS_SCHEDULER.CREATE_JOB(
    JOB_NAME => 'JOB_MAYUS_BRAND_NAME',
    JOB_TYPE => 'STORED_PROCEDURE', -- AQUI SE INDICA EL TIPO DE OBJETO QUE SE LLAMA (FUNCTION | STORED_PROCEDURE)
    JOB_ACTION => 'SP_NOMB_BRAND_MAYUS', -- INDICA EL NOMBRE DEL OBJETO QUE SE QUIERE USAR
    NUMBER_OF_ARGUMENTS => 0, -- SE AGREGA 0 PORQUE EL PROCEDIMIENTO A USAR NO TIENE PARÁMETROS.
    START_DATE => TO_TIMESTAMP('2024-12-12 08:52:00', 'YYYY-MM-DD HH24:MI:SS'), -- FECHA DE INICIO DEL JOB
    REPEAT_INTERVAL => 'FREQ=DAILY',
    ENABLED => TRUE -- SI NO HAY ARGUMENTOS EN EL SP, EL JOB SE INDICA ACTIVO DESDE EL INICIO.
);
END;

-- VER LOS JOBS CREADOS EN LA BASE DE DATOS.
SELECT * FROM USER_SCHEDULER_JOBS;

-- CONSULTA PARA VER LOS JOBS QUE SE HAN EJECUTADO Y SI ESTOS HAN TENIDO ÉXITO EN SU EJECUCIÓN.
SELECT JOB_NAME, LOG_DATE, STATUS FROM USER_SCHEDULER_JOB_LOG;











