SELECT * FROM DBA_ROLES;
SELECT * FROM DBA_USERS;

SELECT * FROM DBA_TAB_PRIVS WHERE GRANTEE = 'C##_USER_BD_BICICLES';
SELECT * FROM DBA_SYS_PRIVS WHERE GRANTEE = 'C##_USER_BD_BICICLES';

-- COMANDO PARA VER LOS USUARIOS VINCULADOS A UN ROL
SELECT GRANTEE FROM DBA_ROLE_PRIVS WHERE GRANTED_ROLE = 'C##_ROLE_ADMINISTRATORS';

GRANT CREATE ANY JOB TO C##_ROLE_ADMINISTRATORS;
